package com.aliyun.sdk.service.oss2.models;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/**
 * The XML body for the CreateJob response.
 */
@JacksonXmlRootElement(localName = "CreateJobResult")
public final class CreateJobResultBody {

    @JacksonXmlProperty(localName = "JobId")
    private String jobId;

    public CreateJobResultBody() {
    }

    private CreateJobResultBody(Builder builder) {
        this.jobId = builder.jobId;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    /**
     * The job ID generated by OSS.
     */
    public String jobId() {
        return this.jobId;
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    public static class Builder {
        private String jobId;

        private Builder() {
            super();
        }

        private Builder(CreateJobResultBody from) {
            this.jobId = from.jobId;
        }

        /**
         * The job ID generated by OSS.
         */
        public Builder jobId(String value) {
            this.jobId = value;
            return this;
        }

        public CreateJobResultBody build() {
            return new CreateJobResultBody(this);
        }
    }
}
